# Generated by Django 5.2.1 on 2026-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_username', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('ADD', 'Tenant Provisioned'), ('DELETE', 'Tenant Purged'), ('ISOLATE', 'Tenant Isolated (Disabled)'), ('ACTIVATE', 'Tenant Activated')], max_length=10)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
